"""Deleted User.birthday and User.zodiac_sign

Revision ID: 24b98806d015
Revises: f7bde67890ce
Create Date: 2025-10-07 14:56:08.124384

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "24b98806d015"
down_revision: Union[str, Sequence[str], None] = "f7bde67890ce"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user", "birthday")
    op.drop_column("user", "zodiac_sign")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "user", sa.Column("zodiac_sign", sa.TEXT(), autoincrement=False, nullable=True)
    )
    op.add_column(
        "user",
        sa.Column(
            "birthday", postgresql.TIMESTAMP(), autoincrement=False, nullable=True
        ),
    )
    # ### end Alembic commands ###
