"""Fix relationship User

Revision ID: 09e4465d4ef1
Revises: 2c9e573ccbdb
Create Date: 2025-10-01 18:02:08.183104

"""

from typing import Sequence, Union


# revision identifiers, used by Alembic.
revision: str = "09e4465d4ef1"
down_revision: Union[str, Sequence[str], None] = "d17efc77bcec"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
