services:
  web:
    image: ghcr.io/astral-sh/uv:python3.11-bookworm
    container_name: prediction_bot_app
    working_dir: /app
    command: >
      sh -c "
        uv sync --frozen &&
        .venv/bin/uvicorn src.app.core.config_run:web_app --host 0.0.0.0 --port 8000
      "
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - static_volume:/app/staticfiles
    depends_on:
      - db

  db:
    image: postgres:15.2
    container_name: postgres_bot
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: ${db_user}
      POSTGRES_PASSWORD: ${db_password}
      POSTGRES_DB: ${db_name}
    volumes:
      - ./pg/var/lib/postgresql/data:/var/lib/postgresql/data
    restart: unless-stopped

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "1336:80"
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - static_volume:/app/staticfiles
    depends_on:
      - web

volumes:
  postgres-data:
  static_volume:
