"""Add field user_timezone

Revision ID: 4add0bdb8085
Revises: 24b98806d015
Create Date: 2025-10-13 15:55:06.751238

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "4add0bdb8085"
down_revision: Union[str, Sequence[str], None] = "24b98806d015"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("user", sa.Column("user_timezone", sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user", "user_timezone")
    # ### end Alembic commands ###
