"""Fix User.uuid

Revision ID: 738a313c64b6
Revises: 6a34211e326a
Create Date: 2025-10-03 11:07:24.603676

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "738a313c64b6"
down_revision: Union[str, Sequence[str], None] = "6a34211e326a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("user", sa.Column("uuid", sa.Text(), nullable=False))
    op.create_unique_constraint(None, "user", ["uuid"])
    op.drop_column("user", "uuid")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "user", sa.Column("uuid", sa.TEXT(), autoincrement=False, nullable=False)
    )
    op.drop_constraint(None, "user", type_="unique")
    op.drop_column("user", "uuid")
    # ### end Alembic commands ###
