"""New session_or_telegram_id

Revision ID: 2c9e573ccbdb
Revises: 11fb707da05b
Create Date: 2025-09-30 13:45:06.881868

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "2c9e573ccbdb"
down_revision: Union[str, Sequence[str], None] = "11fb707da05b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "user", sa.Column("session_or_telegram_id", sa.Text(), nullable=False)
    )
    op.drop_column("user", "uuid")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "user", sa.Column("uuid", sa.UUID(), autoincrement=False, nullable=False)
    )
    op.drop_column("user", "session_or_telegram_id")
    # ### end Alembic commands ###
