"""Проверка

Revision ID: 7bcc81819e4d
Revises: 2ef75c502903
Create Date: 2025-09-16 17:00:35.315740

"""

from typing import Sequence, Union

from alembic import op


# revision identifiers, used by Alembic.
revision: str = "5a73d3a7efa6"
down_revision: Union[str, Sequence[str], None] = "2ef75c502903"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, "prediction", ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "prediction", type_="unique")
    # ### end Alembic commands ###
