"""delete field user_timezone

Revision ID: fc2e85d0020d
Revises: 4add0bdb8085
Create Date: 2025-10-14 12:20:04.029138

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "fc2e85d0020d"
down_revision: Union[str, Sequence[str], None] = "4add0bdb8085"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user", "user_timezone")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "user",
        sa.Column("user_timezone", sa.TEXT(), autoincrement=False, nullable=True),
    )
    # ### end Alembic commands ###
